-- Этот скрипт предназначен для создания (или пересоздания) таблиц в базе данных PostgreSQL.

-- --- Блок удаления (DROP) ---
-- Удаляет существующие таблицы для чистого пересоздания.
-- Порядок важен из-за внешних ключей: сначала удаляется таблица, которая ссылается на другую.

DROP TABLE IF EXISTS public.friendships;
DROP TABLE IF EXISTS public.users;
DROP TABLE IF EXISTS public.images;

-- --- Таблица изображений (images) ---
-- Хранит скачанные изображения.
CREATE TABLE public.images (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    mal_id integer UNIQUE,
    image_url text,
    image_data bytea,
    created_at timestamp with time zone NULL DEFAULT now(),
    CONSTRAINT images_pkey PRIMARY KEY (id)
);


-- --- Таблица пользователей (users) ---
-- Хранит основную информацию о зарегистрированных пользователях.
CREATE TABLE public.users (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NULL DEFAULT now(),
    username text NOT NULL,
    password text NOT NULL,
    list jsonb NULL, -- jsonb для эффективности хранения и запросов к аниме-списку
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_username_key UNIQUE (username)
);

-- --- Таблица дружбы (friendships) ---
-- Хранит связи "многие-ко-многим" между пользователями.
-- Это реализация 3-й нормальной формы для списка друзей.
CREATE TABLE public.friendships (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NULL DEFAULT now(),
    user_id bigint NOT NULL, -- ID пользователя
    friend_id bigint NOT NULL, -- ID друга пользователя
    CONSTRAINT friendships_pkey PRIMARY KEY (id),
    CONSTRAINT friendships_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT friendships_friend_id_fkey FOREIGN KEY (friend_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT friendships_unique_pair UNIQUE (user_id, friend_id) -- Гарантирует, что пара "пользователь-друг" уникальна
);

-- --- Комментарии по использованию ---
-- 1. Таблица `users` содержит всю основную информацию о пользователе.
--    - `username` должен быть уникальным.
--    - `list` хранит аниме-список в формате JSONB, что позволяет эффективно работать с данными.
--
-- 2. Таблица `friendships` создает связь между двумя пользователями.
--    - Когда пользователь A добавляет пользователя B в друзья, рекомендуется создавать две записи:
--      - (user_id: A, friend_id: B)
--      - (user_id: B, friend_id: A)
--      Это обеспечивает "взаимную" дружбу и упрощает запросы на получение списка всех друзей пользователя.
--    - `ON DELETE CASCADE` означает, что если пользователь будет удален из таблицы `users`, все его связи в `friendships` будут автоматически удалены.
